# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.background-update-timer", 1741925406);
user_pref("editor.custom_language", "zh-tw");
user_pref("editor.helpers.browser.args", "");
user_pref("editor.helpers.browser.path", "");
user_pref("editor.helpers.file.args", "");
user_pref("editor.helpers.file.path", "");
user_pref("editor.helpers.ftp.args", "");
user_pref("editor.helpers.ftp.path", "");
user_pref("editor.helpers.image.args", "");
user_pref("editor.helpers.image.path", "");
user_pref("editor.helpers.media.args", "");
user_pref("editor.helpers.media.path", "");
user_pref("editor.helpers.text.args", "");
user_pref("editor.helpers.text.path", "");
user_pref("editor.history_title_0", "圖紙清單");
user_pref("editor.history_title_1", "雲端BIM平台－創優微圖");
user_pref("editor.history_title_2", "雲端BIM平台－創優微圖");
user_pref("editor.history_url_0", "file:///F:/ForgeViewer(New)/Forge%20viewer%20with%20model%20drawing/drawinglist.html");
user_pref("editor.history_url_1", "file:///F:/ForgeViewer(New)/Forge%20viewer%20with%20model%20drawing/Forgeviewerwithdrawing.html");
user_pref("editor.history_url_2", "file:///F:/Users/lclien/Desktop/KompoZerPortable/Forgeviewerwithdrawing.html");
user_pref("editor.lastFileLocation.html", "F:\\ForgeViewer(New)\\Forge viewer with model drawing");
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.lastAppVersion", "0.8b3");
user_pref("extensions.update.notifyUser", false);
user_pref("font.language.group", "zh-TW");
user_pref("font.name.cursive.zh-TW", "標楷體");
user_pref("font.name.fantasy.x-western", "AMGDT");
user_pref("font.name.fantasy.zh-TW", "Arial Unicode MS");
user_pref("intl.charsetmenu.composer.cache", "UTF-8, ISO-8859-1");
user_pref("tipoftheday.openAtStartup", false);
